url: http://www.chrisvanpatten.com
permalink: /blog/:year/:month/:title/
title: Chris Van Patten
owner_link: http://www.chrisvanpatten.com
description: Entrepreneur Chris Van Patten shares tips, stories, and musings at his personal blog.
